"""init

Revision ID: 8761385a2f8c
Revises: 
Create Date: 2026-02-24 13:23:56.786362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8761385a2f8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feriados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('recorrente', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('periodo', sa.String(length=20), nullable=False),
    sa.Column('escala', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('periodos_mensais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes_referencia', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('qtd_sabados', sa.Integer(), nullable=True),
    sa.Column('qtd_domingos', sa.Integer(), nullable=True),
    sa.Column('qtd_feriados', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano', 'mes_referencia', name='uq_periodo_ano_mes')
    )
    with op.batch_alter_table('periodos_mensais', schema=None) as batch_op:
        batch_op.create_index('idx_periodo_datas', ['data_inicio', 'data_fim'], unique=False)

    op.create_table('dias_trabalhados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('dia_semana', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos_mensais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funcionario_id', 'data', name='uq_funcionario_data')
    )
    with op.batch_alter_table('dias_trabalhados', schema=None) as batch_op:
        batch_op.create_index('idx_dia_data', ['data'], unique=False)
        batch_op.create_index('idx_dia_funcionario_periodo', ['funcionario_id', 'periodo_id'], unique=False)

    op.create_table('registro_dia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('trabalhou', sa.Boolean(), nullable=True),
    sa.Column('horas_extras', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_dia')
    with op.batch_alter_table('dias_trabalhados', schema=None) as batch_op:
        batch_op.drop_index('idx_dia_funcionario_periodo')
        batch_op.drop_index('idx_dia_data')

    op.drop_table('dias_trabalhados')
    with op.batch_alter_table('periodos_mensais', schema=None) as batch_op:
        batch_op.drop_index('idx_periodo_datas')

    op.drop_table('periodos_mensais')
    op.drop_table('funcionarios')
    op.drop_table('feriados')
    # ### end Alembic commands ###
